import { ComponentSection } from '../../../../core/models';

/**
 * Configuración de la sección de API del Sidebar Panel
 */
export const SIDEBAR_PANEL_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-import',
    title: 'common.import',
    description: 'common.api.importService',
    anchor: 'api-import',
    examples: [
      {
        title: 'codeExamples.typescript',
        code: `import { SidebarPanelService, SidebarPanelRef, SidebarPanelActionsService, SidebarPanelFooterDirective } from 'nui';
import { SIDEBAR_PANEL_DATA, SIDEBAR_PANEL_REF, SIDEBAR_PANEL_CONFIG } from 'nui';
import type { SidebarPanelConfig, SidebarPanelState, SidebarPanelAction } from 'nui';

@Component({ standalone: true })
export class MyComponent {
  private readonly sidebarPanel = inject(SidebarPanelService);
}`,
        language: 'typescript',
      },
    ],
  },
  {
    id: 'api-service',
    title: 'components.sidebar-panel.api.service.title',
    description: 'components.sidebar-panel.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>open()</code>',
          'component: Type&lt;T&gt;<br>config?: SidebarPanelConfig&lt;D&gt;',
          'SidebarPanelRef&lt;T, R&gt;',
          'components.sidebar-panel.api.service.rows.open',
        ],
        ['<code>close()</code>', 'id: string', 'void', 'components.sidebar-panel.api.service.rows.close'],
        ['<code>closeAll()</code>', '-', 'void', 'components.sidebar-panel.api.service.rows.closeAll'],
        [
          '<code>getPanel()</code>',
          'id: string',
          'SidebarPanelStackItem | undefined',
          'components.sidebar-panel.api.service.rows.getPanel',
        ],
        ['<code>getAllPanels()</code>', '-', 'SidebarPanelStackItem[]', 'components.sidebar-panel.api.service.rows.getAllPanels'],
        ['<code>openPanelsCount</code>', '-', 'number', 'components.sidebar-panel.api.service.rows.openPanelsCount'],
      ],
    },
  },
  {
    id: 'api-ref',
    title: 'components.sidebar-panel.api.ref.title',
    description: 'components.sidebar-panel.api.ref.description',
    anchor: 'api-ref',
    table: {
      headers: ['common.tables.property', 'common.tables.type', 'common.tables.description'],
      rows: [
        ['<code>id</code>', 'string', 'components.sidebar-panel.api.ref.rows.id'],
        ['<code>componentInstance</code>', 'T | null', 'components.sidebar-panel.api.ref.rows.componentInstance'],
        ['<code>config</code>', 'SidebarPanelConfig', 'components.sidebar-panel.api.ref.rows.config'],
        ['<code>state</code>', 'SidebarPanelState', 'components.sidebar-panel.api.ref.rows.state'],
        ['<code>isOpen</code>', 'boolean', 'components.sidebar-panel.api.ref.rows.isOpen'],
        ['<code>isClosed</code>', 'boolean', 'components.sidebar-panel.api.ref.rows.isClosed'],
        ['<code>isMinimized</code>', 'boolean', 'components.sidebar-panel.api.ref.rows.isMinimized'],
        [
          '<code>stateHistory</code>',
          'ReadonlyArray&lt;SidebarPanelState&gt;',
          'components.sidebar-panel.api.ref.rows.stateHistory',
        ],
      ],
    },
  },
  {
    id: 'api-ref-methods',
    title: 'components.sidebar-panel.api.ref-methods.title',
    description: 'components.sidebar-panel.api.ref-methods.description',
    anchor: 'api-ref-methods',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        ['<code>close()</code>', 'result?: R', 'Promise&lt;void&gt;', 'components.sidebar-panel.api.ref.rows.close'],
        ['<code>minimize()</code>', '-', 'void', 'components.sidebar-panel.api.ref.rows.minimize'],
        ['<code>restore()</code>', '-', 'void', 'components.sidebar-panel.api.ref.rows.restore'],
        ['<code>updateTitle()</code>', 'title: string', 'void', 'components.sidebar-panel.api.ref.rows.updateTitle'],
        [
          '<code>updateHeaderTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'components.sidebar-panel.api.ref.rows.updateHeaderTemplate',
        ],
        [
          '<code>updateFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'components.sidebar-panel.api.ref.rows.updateFooterTemplate',
        ],
        [
          '<code>canTransitionTo()</code>',
          'newState: SidebarPanelState',
          'boolean',
          'components.sidebar-panel.api.ref.rows.canTransitionTo',
        ],
        [
          '<code>afterOpened()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.sidebar-panel.api.ref.rows.afterOpened',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;R | undefined&gt;',
          'components.sidebar-panel.api.ref.rows.afterClosed',
        ],
        [
          '<code>backdropClick()</code>',
          '-',
          'Observable&lt;MouseEvent&gt;',
          'components.sidebar-panel.api.ref.rows.backdropClick',
        ],
        [
          '<code>keydownEvents()</code>',
          '-',
          'Observable&lt;KeyboardEvent&gt;',
          'components.sidebar-panel.api.ref.rows.keydownEvents',
        ],
        [
          '<code>stateChanged()</code>',
          '-',
          'Observable&lt;SidebarPanelState&gt;',
          'components.sidebar-panel.api.ref.rows.stateChanged',
        ],
        [
          '<code>closePrevented()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.sidebar-panel.api.ref.rows.closePrevented',
        ],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.sidebar-panel.api.config.title',
    description: 'components.sidebar-panel.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.id',
        ],
        [
          '<code>position</code>',
          "'left' | 'right' | 'top' | 'bottom'",
          '<code class="neutral">right</code>',
          'components.sidebar-panel.api.config.rows.position',
        ],
        [
          '<code>size</code>',
          "NUISize | 'full'",
          '<code class="neutral">md</code>',
          'components.sidebar-panel.api.config.rows.size',
        ],
        [
          '<code>width</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.width',
        ],
        [
          '<code>height</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.height',
        ],
        [
          '<code>maxWidth</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.maxWidth',
        ],
        [
          '<code>maxHeight</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.maxHeight',
        ],
        [
          '<code>data</code>',
          'D',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.data',
        ],
        [
          '<code>contentTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.contentTemplate',
        ],
        [
          '<code>htmlContent</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.htmlContent',
        ],
        [
          '<code>templateContext</code>',
          'any',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.templateContext',
        ],
        ['<code>title</code>', 'string', '<code class="neutral">undefined</code>', 'components.sidebar-panel.api.config.rows.title'],
        ['<code>showHeader</code>', 'boolean', '<code class="neutral">true</code>', 'components.sidebar-panel.api.config.rows.showHeader'],
        [
          '<code>showCloseButton</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.showCloseButton',
        ],
        [
          '<code>headerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.headerTemplate',
        ],
        [
          '<code>footerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.footerTemplate',
        ],
        [
          '<code>customButtons</code>',
          'SidebarPanelCustomButton[]',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.customButtons',
        ],
        [
          '<code>hasBackdrop</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.hasBackdrop',
        ],
        [
          '<code>backdropClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.backdropClass',
        ],
        [
          '<code>closeOnBackdropClick</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.closeOnBackdropClick',
        ],
        [
          '<code>closeOnEscape</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.closeOnEscape',
        ],
        [
          '<code>closeOnRouteChange</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.config.rows.closeOnRouteChange',
        ],
        [
          '<code>preventClose</code>',
          '() =&gt; boolean | Promise&lt;boolean&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.preventClose',
        ],
        [
          '<code>autoFocus</code>',
          'boolean | string',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.autoFocus',
        ],
        [
          '<code>mobileFullScreen</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.config.rows.mobileFullScreen',
        ],
        [
          '<code>panelClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.panelClass',
        ],
        [
          '<code>scrollStrategy</code>',
          "'block' | 'reposition' | 'close'",
          '<code class="neutral">block</code>',
          'components.sidebar-panel.api.config.rows.scrollStrategy',
        ],
        [
          '<code>animationDuration</code>',
          'number',
          '<code class="neutral">300</code>',
          'components.sidebar-panel.api.config.rows.animationDuration',
        ],
        ['<code>zIndex</code>', 'number', '<code class="neutral">1040</code>', 'components.sidebar-panel.api.config.rows.zIndex'],
        [
          '<code>minimizable</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.config.rows.minimizable',
        ],
        [
          '<code>dockTabConfig</code>',
          'DockTabConfig',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.dockTabConfig',
        ],
        [
          '<code>allowMultiple</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.config.rows.allowMultiple',
        ],
        [
          '<code>lazyLoad</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.sidebar-panel.api.config.rows.lazyLoad',
        ],
        [
          '<code>ariaLabel</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.ariaLabel',
        ],
        [
          '<code>ariaDescribedBy</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.config.rows.ariaDescribedBy',
        ],
      ],
    },
  },
  {
    id: 'api-custom-button',
    title: 'components.sidebar-panel.api.custom-button.title',
    description: 'components.sidebar-panel.api.custom-button.description',
    anchor: 'api-custom-button',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>text</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.text',
        ],
        [
          '<code>prefixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.prefixIcon',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.suffixIcon',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.color',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.variant',
        ],
        ['<code>size</code>', 'NUISize', '<code class="neutral">undefined</code>', 'components.sidebar-panel.api.custom-button.rows.size'],
        [
          '<code>callback</code>',
          '(panelRef: SidebarPanelRef) =&gt; void | Promise&lt;void&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.callback',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.custom-button.rows.disabled',
        ],
        [
          '<code>loading</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.custom-button.rows.loading',
        ],
        [
          '<code>loadingPosition</code>',
          'ButtonLoadingPosition',
          '<code class="neutral">center</code>',
          'components.sidebar-panel.api.custom-button.rows.loadingPosition',
        ],
        [
          '<code>class</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.custom-button.rows.class',
        ],
        [
          '<code>width</code>',
          'ButtonWidth',
          '<code class="neutral">auto</code>',
          'components.sidebar-panel.api.custom-button.rows.width',
        ],
      ],
    },
  },
  {
    id: 'api-minimized-tab',
    title: 'components.sidebar-panel.api.minimized-tab.title',
    description: 'components.sidebar-panel.api.minimized-tab.description',
    anchor: 'api-minimized-tab',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>prefixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.minimized-tab.rows.prefixIcon',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.minimized-tab.rows.suffixIcon',
        ],
        [
          '<code>hideSuffixIcon</code>',
          'boolean',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.minimized-tab.rows.hideSuffixIcon',
        ],
        [
          '<code>label</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.minimized-tab.rows.label',
        ],
        [
          '<code>cssClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.minimized-tab.rows.cssClass',
        ],
      ],
    },
  },
  {
    id: 'api-footer-actions',
    title: 'components.sidebar-panel.api.footer-actions.title',
    description: 'components.sidebar-panel.api.footer-actions.description',
    anchor: 'api-footer-actions',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.id',
        ],
        [
          '<code>label</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.label',
        ],
        [
          '<code>prefixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.prefixIcon',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.suffixIcon',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.color',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.variant',
        ],
        ['<code>size</code>', 'NUISize', '<code class="neutral">undefined</code>', 'components.sidebar-panel.api.footer-actions.rows.size'],
        [
          '<code>handler</code>',
          '() =&gt; void | Promise&lt;void&gt;',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.handler',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.footer-actions.rows.disabled',
        ],
        [
          '<code>loading</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.sidebar-panel.api.footer-actions.rows.loading',
        ],
        [
          '<code>loadingPosition</code>',
          'ButtonLoadingPosition',
          '<code class="neutral">center</code>',
          'components.sidebar-panel.api.footer-actions.rows.loadingPosition',
        ],
        [
          '<code>class</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.sidebar-panel.api.footer-actions.rows.class',
        ],
        [
          '<code>width</code>',
          'ButtonWidth',
          '<code class="neutral">auto</code>',
          'components.sidebar-panel.api.footer-actions.rows.width',
        ],
      ],
    },
  },
  {
    id: 'api-footer-actions-service',
    title: 'components.sidebar-panel.api.footer-actions-service.title',
    description: 'components.sidebar-panel.api.footer-actions-service.description',
    anchor: 'api-footer-actions-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>register()</code>',
          'actions: SidebarPanelAction[]',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.register',
        ],
        [
          '<code>add()</code>',
          'action: SidebarPanelAction',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.add',
        ],
        [
          '<code>update()</code>',
          'index: number, updates: Partial&lt;SidebarPanelAction&gt;',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.update',
        ],
        [
          '<code>updateById()</code>',
          'id: string, updates: Partial&lt;SidebarPanelAction&gt;',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.updateById',
        ],
        ['<code>clear()</code>', '-', 'void', 'components.sidebar-panel.api.footer-actions-service.rows.clear'],
        [
          '<code>setDisabled()</code>',
          'index: number, disabled: boolean',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.setDisabled',
        ],
        [
          '<code>setLoading()</code>',
          'index: number, loading: boolean',
          'void',
          'components.sidebar-panel.api.footer-actions-service.rows.setLoading',
        ],
      ],
    },
  },
  {
    id: 'api-footer-directive',
    title: 'components.sidebar-panel.api.footer-directive.title',
    description: 'components.sidebar-panel.api.footer-directive.description',
    anchor: 'api-footer-directive',
  },
  {
    id: 'api-tokens',
    title: 'components.sidebar-panel.api.tokens.title',
    description: 'components.sidebar-panel.api.tokens.description',
    anchor: 'api-tokens',
    table: {
      headers: ['common.tables.token', 'common.tables.type', 'common.tables.description'],
      rows: [
        [
          '<code>SIDEBAR_PANEL_DATA</code>',
          'InjectionToken&lt;D&gt;',
          'components.sidebar-panel.api.tokens.rows.SIDEBAR_PANEL_DATA',
        ],
        [
          '<code>SIDEBAR_PANEL_REF</code>',
          'InjectionToken&lt;SidebarPanelRef&gt;',
          'components.sidebar-panel.api.tokens.rows.SIDEBAR_PANEL_REF',
        ],
        [
          '<code>SIDEBAR_PANEL_CONFIG</code>',
          'InjectionToken&lt;SidebarPanelConfig&gt;',
          'components.sidebar-panel.api.tokens.rows.SIDEBAR_PANEL_CONFIG',
        ],
      ],
    },
  },
];
