import { ComponentSection } from '../../../../core/models';

/**
 * Configuración de la sección de API del Sidebar Panel
 */
export const SIDEBAR_PANEL_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-service',
    title: 'components.sidebar-panel.api.service.title',
    description: 'components.sidebar-panel.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>open()</code>',
          'component: Type&lt;T&gt;<br>config?: SidebarPanelConfig&lt;D&gt;',
          'SidebarPanelRef&lt;T, R&gt;',
          'Opens a panel with a dynamic component',
        ],
        ['<code>close()</code>', 'id: string', 'void', 'Closes a specific panel by ID'],
        ['<code>closeAll()</code>', '-', 'void', 'Closes all open panels'],
        [
          '<code>getPanel()</code>',
          'id: string',
          'SidebarPanelStackItem | undefined',
          'Gets a panel by its ID',
        ],
        ['<code>getAllPanels()</code>', '-', 'SidebarPanelStackItem[]', 'Gets all open panels'],
        ['<code>openPanelsCount</code>', '-', 'number', 'Number of currently open panels (getter)'],
      ],
    },
  },
  {
    id: 'api-ref-properties',
    title: 'components.sidebar-panel.api.ref-properties.title',
    description: 'components.sidebar-panel.api.ref-properties.description',
    anchor: 'api-ref-properties',
    table: {
      headers: ['common.tables.property', 'common.tables.type', 'common.tables.description'],
      rows: [
        ['<code>id</code>', 'string', 'Unique panel ID'],
        ['<code>componentInstance</code>', 'T | null', 'Instance of the loaded component'],
        ['<code>config</code>', 'SidebarPanelConfig', 'Panel configuration'],
        ['<code>state</code>', 'SidebarPanelState', 'Current panel state'],
        ['<code>isOpen</code>', 'boolean', 'true if panel is open or opening'],
        ['<code>isClosed</code>', 'boolean', 'true if panel is closed or closing'],
        ['<code>isMinimized</code>', 'boolean', 'true if panel is minimized'],
        [
          '<code>stateHistory</code>',
          'ReadonlyArray&lt;SidebarPanelState&gt;',
          'History of panel states',
        ],
      ],
    },
  },
  {
    id: 'api-ref-methods',
    title: 'components.sidebar-panel.api.ref-methods.title',
    description: 'components.sidebar-panel.api.ref-methods.description',
    anchor: 'api-ref-methods',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        ['<code>close()</code>', 'result?: R', 'Promise&lt;void&gt;', 'Closes the panel'],
        ['<code>minimize()</code>', '-', 'void', 'Minimizes the panel (if minimizable: true)'],
        ['<code>restore()</code>', '-', 'void', 'Restores the panel from minimized state'],
        ['<code>updateTitle()</code>', 'title: string', 'void', 'Updates the panel title'],
        [
          '<code>updateHeaderTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the header template',
        ],
        [
          '<code>updateFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the footer template',
        ],
        [
          '<code>canTransitionTo()</code>',
          'newState: SidebarPanelState',
          'boolean',
          'Checks if the panel can transition to a new state',
        ],
        [
          '<code>afterOpened()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emitted after panel is fully opened',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;R | undefined&gt;',
          'Emitted after panel is closed',
        ],
        [
          '<code>backdropClick()</code>',
          '-',
          'Observable&lt;MouseEvent&gt;',
          'Emitted when backdrop is clicked',
        ],
        [
          '<code>keydownEvents()</code>',
          '-',
          'Observable&lt;KeyboardEvent&gt;',
          'Emitted on each keydown inside the panel',
        ],
        [
          '<code>stateChanged()</code>',
          '-',
          'Observable&lt;SidebarPanelState&gt;',
          'Emitted when panel state changes',
        ],
        [
          '<code>closePrevented()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emitted when close is prevented',
        ],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.sidebar-panel.api.config.title',
    description: 'components.sidebar-panel.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Panel ID (required if minimizable: true)',
        ],
        [
          '<code>position</code>',
          "'left' | 'right' | 'top' | 'bottom'",
          '<code class="neutral">right</code>',
          'Panel position on screen',
        ],
        [
          '<code>size</code>',
          "NUISize | 'full'",
          '<code class="neutral">md</code>',
          'Predefined panel size',
        ],
        [
          '<code>width</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom width (for left/right)',
        ],
        [
          '<code>height</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom height (for top/bottom)',
        ],
        [
          '<code>data</code>',
          'D',
          '<code class="neutral">undefined</code>',
          'Data passed to the component',
        ],
        [
          '<code>contentTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Angular template as content',
        ],
        [
          '<code>htmlContent</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'HTML string as content',
        ],
        [
          '<code>templateContext</code>',
          'any',
          '<code class="neutral">undefined</code>',
          'Context for the template',
        ],
        ['<code>title</code>', 'string', '<code class="neutral">undefined</code>', 'Panel title'],
        ['<code>showHeader</code>', 'boolean', '<code class="neutral">true</code>', 'Show header'],
        [
          '<code>showCloseButton</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Show close button',
        ],
        [
          '<code>headerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Custom header template',
        ],
        [
          '<code>footerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Custom footer template',
        ],
        [
          '<code>customButtons</code>',
          'SidebarPanelCustomButton[]',
          '<code class="neutral">undefined</code>',
          'Footer buttons',
        ],
        [
          '<code>hasBackdrop</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Show backdrop',
        ],
        [
          '<code>backdropClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Backdrop CSS classes',
        ],
        [
          '<code>closeOnBackdropClick</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Close on backdrop click',
        ],
        [
          '<code>closeOnEscape</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Close on Escape key',
        ],
        [
          '<code>closeOnRouteChange</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Close on route change',
        ],
        [
          '<code>preventClose</code>',
          '() =&gt; boolean | Promise&lt;boolean&gt;',
          '<code class="neutral">undefined</code>',
          'Guard before closing',
        ],
        [
          '<code>autoFocus</code>',
          'boolean | string',
          '<code class="neutral">true</code>',
          'Auto-focus behavior',
        ],
        [
          '<code>mobileFullScreen</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Fullscreen on mobile',
        ],
        [
          '<code>breakpoint</code>',
          'number',
          '<code class="neutral">768</code>',
          'Mobile breakpoint in px',
        ],
        [
          '<code>panelClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Additional panel CSS classes',
        ],
        [
          '<code>scrollStrategy</code>',
          "'block' | 'reposition' | 'close'",
          '<code class="neutral">block</code>',
          'Body scroll strategy',
        ],
        [
          '<code>animationDuration</code>',
          'number',
          '<code class="neutral">225</code>',
          'Animation duration in ms',
        ],
        ['<code>zIndex</code>', 'number', '<code class="neutral">1000</code>', 'Base z-index'],
        [
          '<code>minimizable</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Panel can be minimized',
        ],
        [
          '<code>minimizedTabCustomization</code>',
          'MinimizedTabCustomization',
          '<code class="neutral">undefined</code>',
          'Minimized tab customization',
        ],
        [
          '<code>allowMultiple</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Allow multiple panels',
        ],
        [
          '<code>lazyLoad</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Lazy load content',
        ],
        [
          '<code>ariaLabel</code>',
          'string',
          '<code class="neutral">Slide Panel</code>',
          'ARIA label',
        ],
        [
          '<code>ariaDescribedBy</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'ARIA describedBy ID',
        ],
      ],
    },
  },
  {
    id: 'api-custom-button',
    title: 'components.sidebar-panel.api.custom-button.title',
    description: 'components.sidebar-panel.api.custom-button.description',
    anchor: 'api-custom-button',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>text</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Button label (required)',
        ],
        [
          '<code>icon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Remix Icon class (e.g., ri-save-line)',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'Button color',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '<code class="neutral">undefined</code>',
          'Button variant (solid, outline, ghost)',
        ],
        ['<code>size</code>', 'NUISize', '<code class="neutral">undefined</code>', 'Button size'],
        [
          '<code>callback</code>',
          '(panelRef: SidebarPanelRef) =&gt; void | Promise&lt;void&gt;',
          '<code class="neutral">undefined</code>',
          'Click handler (required)',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Disabled state',
        ],
        [
          '<code>loading</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Show loading spinner',
        ],
        [
          '<code>class</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Additional CSS classes',
        ],
      ],
    },
  },
  {
    id: 'api-minimized-tab',
    title: 'components.sidebar-panel.api.minimized-tab.title',
    description: 'components.sidebar-panel.api.minimized-tab.description',
    anchor: 'api-minimized-tab',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>icon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom tab icon (Remix Icon)',
        ],
        [
          '<code>label</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom tab label',
        ],
        [
          '<code>cssClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Additional tab CSS classes',
        ],
        [
          '<code>template</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Fully custom tab template',
        ],
        [
          '<code>standalone</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Render outside grouped container (free positioning)',
        ],
      ],
    },
  },
];
