import { ComponentSection } from '../../../../core/models';

/**
 * Configuración de la sección de API del Sidebar Panel
 */
export const SIDEBAR_PANEL_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-service',
    title: 'components.sidebar-panel.api.service.title',
    description: 'components.sidebar-panel.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>open()</code>',
          'component: Type&lt;T&gt;<br>config?: SidebarPanelConfig&lt;D&gt;',
          'SidebarPanelRef&lt;T, R&gt;',
          'Opens a panel with a dynamic component',
        ],
        ['<code>close()</code>', 'id: string', 'void', 'Closes a specific panel by ID'],
        ['<code>closeAll()</code>', '-', 'void', 'Closes all open panels'],
        [
          '<code>getPanel()</code>',
          'id: string',
          'SidebarPanelStackItem | undefined',
          'Gets a panel by its ID',
        ],
        ['<code>getAllPanels()</code>', '-', 'SidebarPanelStackItem[]', 'Gets all open panels'],
        ['<code>openPanelsCount</code>', '-', 'number', 'Number of currently open panels (getter)'],
      ],
    },
  },
  {
    id: 'api-ref',
    title: 'components.sidebar-panel.api.ref.title',
    description: 'components.sidebar-panel.api.ref.description',
    anchor: 'api-ref',
    table: {
      headers: ['common.tables.property', 'common.tables.type', 'common.tables.description'],
      rows: [
        ['<code>id</code>', 'string', 'Unique panel ID'],
        ['<code>componentInstance</code>', 'T | null', 'Instance of the loaded component'],
        ['<code>config</code>', 'SidebarPanelConfig', 'Panel configuration'],
        ['<code>state</code>', 'SidebarPanelState', 'Current panel state'],
        ['<code>isOpen</code>', 'boolean', 'true if panel is open or opening'],
        ['<code>isClosed</code>', 'boolean', 'true if panel is closed or closing'],
        ['<code>isMinimized</code>', 'boolean', 'true if panel is minimized'],
        [
          '<code>stateHistory</code>',
          'ReadonlyArray&lt;SidebarPanelState&gt;',
          'History of panel states',
        ],
        ['<code>close()</code>', 'result?: R', 'Promise&lt;void&gt;', 'Closes the panel'],
        ['<code>minimize()</code>', '-', 'void', 'Minimizes the panel (if minimizable: true)'],
        ['<code>restore()</code>', '-', 'void', 'Restores the panel from minimized state'],
        ['<code>updateTitle()</code>', 'title: string', 'void', 'Updates the panel title'],
        [
          '<code>updateHeaderTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the header template',
        ],
        [
          '<code>updateFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the footer template',
        ],
        [
          '<code>canTransitionTo()</code>',
          'newState: SidebarPanelState',
          'boolean',
          'Checks if the panel can transition to a new state',
        ],
        [
          '<code>afterOpened()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emitted after panel is fully opened',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;R | undefined&gt;',
          'Emitted after panel is closed',
        ],
        [
          '<code>backdropClick()</code>',
          '-',
          'Observable&lt;MouseEvent&gt;',
          'Emitted when backdrop is clicked',
        ],
        [
          '<code>keydownEvents()</code>',
          '-',
          'Observable&lt;KeyboardEvent&gt;',
          'Emitted on each keydown inside the panel',
        ],
        [
          '<code>stateChanged()</code>',
          '-',
          'Observable&lt;SidebarPanelState&gt;',
          'Emitted when panel state changes',
        ],
        [
          '<code>closePrevented()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emitted when close is prevented',
        ],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.sidebar-panel.api.config.title',
    description: 'components.sidebar-panel.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Panel ID (required if minimizable: true)',
        ],
        [
          '<code>position</code>',
          "'left' | 'right' | 'top' | 'bottom'",
          '<code class="neutral">right</code>',
          'Panel position on screen',
        ],
        [
          '<code>size</code>',
          "NUISize | 'full'",
          '<code class="neutral">md</code>',
          'Predefined panel size',
        ],
        [
          '<code>width</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom width (for left/right)',
        ],
        [
          '<code>height</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom height (for top/bottom)',
        ],
        [
          '<code>data</code>',
          'D',
          '<code class="neutral">undefined</code>',
          'Data passed to the component',
        ],
        [
          '<code>contentTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Angular template as content',
        ],
        [
          '<code>htmlContent</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'HTML string as content',
        ],
        [
          '<code>templateContext</code>',
          'any',
          '<code class="neutral">undefined</code>',
          'Context for the template',
        ],
        ['<code>title</code>', 'string', '<code class="neutral">undefined</code>', 'Panel title'],
        ['<code>showHeader</code>', 'boolean', '<code class="neutral">true</code>', 'Show header'],
        [
          '<code>showCloseButton</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Show close button',
        ],
        [
          '<code>headerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Custom header template',
        ],
        [
          '<code>footerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Custom footer template',
        ],
        [
          '<code>customButtons</code>',
          'SidebarPanelCustomButton[]',
          '<code class="neutral">undefined</code>',
          'Footer buttons',
        ],
        [
          '<code>hasBackdrop</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Show backdrop',
        ],
        [
          '<code>backdropClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Backdrop CSS classes',
        ],
        [
          '<code>closeOnBackdropClick</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Close on backdrop click',
        ],
        [
          '<code>closeOnEscape</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Close on Escape key',
        ],
        [
          '<code>closeOnRouteChange</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Close on route change',
        ],
        [
          '<code>preventClose</code>',
          '() =&gt; boolean | Promise&lt;boolean&gt;',
          '<code class="neutral">undefined</code>',
          'Guard before closing',
        ],
        [
          '<code>autoFocus</code>',
          'boolean | string',
          '<code class="neutral">true</code>',
          'Auto-focus behavior',
        ],
        [
          '<code>mobileFullScreen</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Fullscreen on mobile',
        ],
        [
          '<code>panelClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Additional panel CSS classes',
        ],
        [
          '<code>scrollStrategy</code>',
          "'block' | 'reposition' | 'close'",
          '<code class="neutral">block</code>',
          'Body scroll strategy',
        ],
        [
          '<code>animationDuration</code>',
          'number',
          '<code class="neutral">225</code>',
          'Animation duration in ms',
        ],
        ['<code>zIndex</code>', 'number', '<code class="neutral">1000</code>', 'Base z-index'],
        [
          '<code>minimizable</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Panel can be minimized',
        ],
        [
          '<code>minimizedTabCustomization</code>',
          'MinimizedTabCustomization',
          '<code class="neutral">undefined</code>',
          'Minimized tab customization',
        ],
        [
          '<code>allowMultiple</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Allow multiple panels',
        ],
        [
          '<code>lazyLoad</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'Lazy load content',
        ],
        [
          '<code>ariaLabel</code>',
          'string',
          '<code class="neutral">Slide Panel</code>',
          'ARIA label',
        ],
        [
          '<code>ariaDescribedBy</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'ARIA describedBy ID',
        ],
      ],
    },
  },
  {
    id: 'api-custom-button',
    title: 'components.sidebar-panel.api.custom-button.title',
    description: 'components.sidebar-panel.api.custom-button.description',
    anchor: 'api-custom-button',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>text</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Button label (required)',
        ],
        [
          '<code>icon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Remix Icon class (e.g., ri-save-line)',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'Button color',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '<code class="neutral">undefined</code>',
          'Button variant (solid, outline, ghost)',
        ],
        ['<code>size</code>', 'NUISize', '<code class="neutral">undefined</code>', 'Button size'],
        [
          '<code>callback</code>',
          '(panelRef: SidebarPanelRef) =&gt; void | Promise&lt;void&gt;',
          '<code class="neutral">undefined</code>',
          'Click handler (required)',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Disabled state',
        ],
        [
          '<code>loading</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Show loading spinner',
        ],
        [
          '<code>class</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Additional CSS classes',
        ],
      ],
    },
  },
  {
    id: 'api-minimized-tab',
    title: 'components.sidebar-panel.api.minimized-tab.title',
    description: 'components.sidebar-panel.api.minimized-tab.description',
    anchor: 'api-minimized-tab',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>icon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom tab icon (Remix Icon)',
        ],
        [
          '<code>label</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Custom tab label',
        ],
        [
          '<code>cssClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'Additional tab CSS classes',
        ],
        [
          '<code>template</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'Fully custom tab template',
        ],
        [
          '<code>standalone</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Render outside grouped container (free positioning)',
        ],
      ],
    },
  },
  {
    id: 'api-footer-actions',
    title: 'components.sidebar-panel.api.footer-actions.title',
    description: 'components.sidebar-panel.api.footer-actions.description',
    anchor: 'api-footer-actions',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Unique action ID (optional, useful for dynamic updates)',
        ],
        [
          '<code>label</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Button label (required)',
        ],
        [
          '<code>icon</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Remix Icon class (e.g., ri-save-line)',
        ],
        [
          '<code>iconPosition</code>',
          "'start' | 'end'",
          '<code class="neutral">start</code>',
          'Icon position relative to label',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'Button color',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '<code class="neutral">undefined</code>',
          'Button variant (solid, outline, ghost)',
        ],
        ['<code>size</code>', 'NUISize', '<code class="neutral">undefined</code>', 'Button size'],
        [
          '<code>handler</code>',
          '() =&gt; void | Promise&lt;void&gt;',
          '<code class="neutral">undefined</code>',
          'Click handler (required)',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Disabled state',
        ],
        [
          '<code>loading</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'Show loading spinner',
        ],
        [
          '<code>loadingPosition</code>',
          "'start' | 'end'",
          '<code class="neutral">start</code>',
          'Loading spinner position',
        ],
        [
          '<code>class</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'Additional CSS classes',
        ],
        [
          '<code>width</code>',
          "'auto' | 'full'",
          '<code class="neutral">auto</code>',
          'Button width',
        ],
      ],
    },
  },
  {
    id: 'api-footer-actions-service',
    title: 'components.sidebar-panel.api.footer-actions-service.title',
    description: 'components.sidebar-panel.api.footer-actions-service.description',
    anchor: 'api-footer-actions-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>register()</code>',
          'actions: SidebarPanelAction[]',
          'void',
          'Registers a set of footer actions, replacing any existing ones',
        ],
        [
          '<code>add()</code>',
          'action: SidebarPanelAction',
          'void',
          'Adds a single action to the existing set',
        ],
        [
          '<code>update()</code>',
          'index: number, updates: Partial&lt;SidebarPanelAction&gt;',
          'void',
          'Updates an action by its index',
        ],
        [
          '<code>updateById()</code>',
          'id: string, updates: Partial&lt;SidebarPanelAction&gt;',
          'void',
          'Updates an action by its ID',
        ],
        ['<code>clear()</code>', '-', 'void', 'Removes all registered actions'],
        [
          '<code>setDisabled()</code>',
          'index: number, disabled: boolean',
          'void',
          'Sets the disabled state of an action by index',
        ],
        [
          '<code>setLoading()</code>',
          'index: number, loading: boolean',
          'void',
          'Sets the loading state of an action by index',
        ],
      ],
    },
  },
  {
    id: 'api-footer-directive',
    title: 'components.sidebar-panel.api.footer-directive.title',
    description: 'components.sidebar-panel.api.footer-directive.description',
    anchor: 'api-footer-directive',
  },
  {
    id: 'api-tokens',
    title: 'components.sidebar-panel.api.tokens.title',
    description: 'components.sidebar-panel.api.tokens.description',
    anchor: 'api-tokens',
    table: {
      headers: ['common.tables.token', 'common.tables.type', 'common.tables.description'],
      rows: [
        [
          '<code>SIDEBAR_PANEL_DATA</code>',
          'InjectionToken&lt;D&gt;',
          'Inject typed data in the dynamic component',
        ],
        [
          '<code>SIDEBAR_PANEL_REF</code>',
          'InjectionToken&lt;SidebarPanelRef&gt;',
          'Inject the sidebar panel reference in the shell or dynamic component',
        ],
        [
          '<code>SIDEBAR_PANEL_CONFIG</code>',
          'InjectionToken&lt;SidebarPanelConfig&gt;',
          'Inject the full configuration object (read-only)',
        ],
      ],
    },
  },
];
