import { ComponentSection } from '../../../../core/models';

/**
 * Configuración de las secciones de API del Toast
 */
export const TOAST_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-import',
    title: 'common.import',
    description: 'common.api.importService',
    anchor: 'api-import',
    examples: [
      {
        title: 'codeExamples.typescript',
        code: `import { ToastService } from 'nui';

@Component({ standalone: true })
export class MyComponent {
  private readonly toast = inject(ToastService);
}`,
        language: 'typescript',
      },
    ],
  },
  {
    id: 'api-service',
    title: 'components.toast.api.service.title',
    description: 'components.toast.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>success()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.success.description',
        ],
        [
          '<code>error()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.error.description',
        ],
        [
          '<code>warning()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.warning.description',
        ],
        [
          '<code>info()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.info.description',
        ],
        [
          '<code>custom()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.custom.description',
        ],
        [
          '<code>loading()</code>',
          'message: string, options?: ToastConfig',
          'ToastRef',
          'components.toast.api.service.rows.loading.description',
        ],
        [
          '<code>promise()</code>',
          'promise: Promise&lt;T&gt;, messages: { loading: string; success: string | ((r: T) =&gt; string); error: string | ((e: any) =&gt; string) }, options?: ToastConfig',
          'Promise&lt;T&gt;',
          'components.toast.api.service.rows.promise.description',
        ],
        [
          '<code>update()</code>',
          'id: string, options: Partial&lt;ToastConfig&gt;',
          'void',
          'components.toast.api.service.rows.update.description',
        ],
        [
          '<code>close()</code>',
          'id: string',
          'void',
          'components.toast.api.service.rows.close.description',
        ],
        [
          '<code>closeAll()</code>',
          '-',
          'void',
          'components.toast.api.service.rows.closeAll.description',
        ],
        [
          '<code>closeGroup()</code>',
          'group: string',
          'void',
          'components.toast.api.service.rows.closeGroup.description',
        ],
        [
          '<code>closeByType()</code>',
          'type: ToastType',
          'void',
          'components.toast.api.service.rows.closeByType.description',
        ],
        [
          '<code>get()</code>',
          'id: string',
          'ToastRef | undefined',
          'components.toast.api.service.rows.get.description',
        ],
        [
          '<code>getActive()</code>',
          '-',
          'ToastRef[]',
          'components.toast.api.service.rows.getActive.description',
        ],
        [
          '<code>getGroup()</code>',
          'group: string',
          'ToastRef[]',
          'components.toast.api.service.rows.getGroup.description',
        ],
        [
          '<code>clearPersistent()</code>',
          '-',
          'void',
          'components.toast.api.service.rows.clearPersistent.description',
        ],
      ],
    },
  },
  {
    id: 'api-ref',
    title: 'components.toast.api.ref.title',
    description: 'components.toast.api.ref.description',
    anchor: 'api-ref',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>close()</code>',
          '-',
          'void',
          'components.toast.api.ref.rows.close.description',
        ],
        [
          '<code>update()</code>',
          'options: Partial&lt;ToastConfig&gt;',
          'void',
          'components.toast.api.ref.rows.update.description',
        ],
        [
          '<code>pause()</code>',
          '-',
          'void',
          'components.toast.api.ref.rows.pause.description',
        ],
        [
          '<code>resume()</code>',
          '-',
          'void',
          'components.toast.api.ref.rows.resume.description',
        ],
        [
          '<code>resetTimeout()</code>',
          '-',
          'void',
          'components.toast.api.ref.rows.resetTimeout.description',
        ],
        [
          '<code>toggleExpanded()</code>',
          '-',
          'void',
          'components.toast.api.ref.rows.toggleExpanded.description',
        ],
        [
          '<code>getState()</code>',
          '-',
          'ToastState',
          'components.toast.api.ref.rows.getState.description',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.toast.api.ref.rows.afterClosed.description',
        ],
        [
          '<code>afterShown()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.toast.api.ref.rows.afterShown.description',
        ],
        [
          '<code>onPause()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.toast.api.ref.rows.onPause.description',
        ],
        [
          '<code>onResume()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.toast.api.ref.rows.onResume.description',
        ],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.toast.api.config.title',
    description: 'components.toast.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>type</code>',
          'ToastType',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.type.description',
        ],
        [
          '<code>title</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.title.description',
        ],
        [
          '<code>message</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.message.description',
        ],
        [
          '<code>html</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.html.description',
        ],
        [
          '<code>template</code>',
          'TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.template.description',
        ],
        [
          '<code>templateContext</code>',
          'any',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.templateContext.description',
        ],
        [
          '<code>templateMode</code>',
          "'replace' | 'append'",
          '<code class="neutral">replace</code>',
          'components.toast.api.config.rows.templateMode.description',
        ],
        [
          '<code>icon</code>',
          'boolean | string',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.icon.description',
        ],
        [
          '<code>iconPosition</code>',
          "'left' | 'top'",
          '<code class="neutral">left</code>',
          'components.toast.api.config.rows.iconPosition.description',
        ],
        [
          '<code>toastClass</code>',
          'string | string[]',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.toastClass.description',
        ],
        [
          '<code>action</code>',
          'ToastAction',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.action.description',
        ],
        [
          '<code>actions</code>',
          'ToastAction[]',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.actions.description',
        ],
        [
          '<code>timeout</code>',
          'number',
          '<code class="neutral">5000</code>',
          'components.toast.api.config.rows.timeout.description',
        ],
        [
          '<code>progressBar</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.progressBar.description',
        ],
        [
          '<code>closeButton</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.closeButton.description',
        ],
        [
          '<code>pauseOnHover</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.pauseOnHover.description',
        ],
        [
          '<code>pauseOnFocusLoss</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.pauseOnFocusLoss.description',
        ],
        [
          '<code>closeOnTouch</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.closeOnTouch.description',
        ],
        [
          '<code>swipeToDismiss</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.swipeToDismiss.description',
        ],
        [
          '<code>swipeThreshold</code>',
          'number',
          '<code class="neutral">100</code>',
          'components.toast.api.config.rows.swipeThreshold.description',
        ],
        [
          '<code>position</code>',
          'ToastPosition',
          '<code class="neutral">top-right</code>',
          'components.toast.api.config.rows.position.description',
        ],
        [
          '<code>animationIn</code>',
          "'slide' | 'fade' | 'bounce' | 'zoom' | 'flip'",
          '<code class="neutral">slide</code>',
          'components.toast.api.config.rows.animationIn.description',
        ],
        [
          '<code>animationOut</code>',
          "'slide' | 'fade' | 'shrink' | 'zoom'",
          '<code class="neutral">fade</code>',
          'components.toast.api.config.rows.animationOut.description',
        ],
        [
          '<code>animationDuration</code>',
          'number',
          '<code class="neutral">300</code>',
          'components.toast.api.config.rows.animationDuration.description',
        ],
        [
          '<code>group</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.group.description',
        ],
        [
          '<code>priority</code>',
          'number',
          '<code class="neutral">0</code>',
          'components.toast.api.config.rows.priority.description',
        ],
        [
          '<code>id</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.id.description',
        ],
        [
          '<code>persistent</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.toast.api.config.rows.persistent.description',
        ],
        [
          '<code>persistentId</code>',
          'string',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.persistentId.description',
        ],
        [
          '<code>expandable</code>',
          'boolean',
          '<code class="neutral">false</code>',
          'components.toast.api.config.rows.expandable.description',
        ],
        [
          '<code>expandedContent</code>',
          'string | TemplateRef&lt;any&gt;',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.expandedContent.description',
        ],
        [
          '<code>sound</code>',
          'boolean | string',
          '<code class="neutral">false</code>',
          'components.toast.api.config.rows.sound.description',
        ],
        [
          '<code>requireOnline</code>',
          'boolean',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.requireOnline.description',
        ],
        [
          '<code>ariaRole</code>',
          "'status' | 'alert' | 'log'",
          '<code class="neutral">status</code>',
          'components.toast.api.config.rows.ariaRole.description',
        ],
        [
          '<code>ariaLive</code>',
          "'polite' | 'assertive' | 'off'",
          '<code class="neutral">polite</code>',
          'components.toast.api.config.rows.ariaLive.description',
        ],
        [
          '<code>announceToScreenReader</code>',
          'boolean',
          '<code class="neutral">true</code>',
          'components.toast.api.config.rows.announceToScreenReader.description',
        ],
        [
          '<code>buttonsSize</code>',
          'NUISize',
          '<code class="neutral">sm</code>',
          'components.toast.api.config.rows.buttonsSize.description',
        ],
        [
          '<code>buttonsColor</code>',
          'NUIColor',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.buttonsColor.description',
        ],
        [
          '<code>buttonsVariant</code>',
          'NUIVariant',
          '<code class="neutral">ghost</code>',
          'components.toast.api.config.rows.buttonsVariant.description',
        ],
        [
          '<code>buttonsShape</code>',
          'NUIShape',
          '<code class="neutral">rounded</code>',
          'components.toast.api.config.rows.buttonsShape.description',
        ],
        [
          '<code>onShown</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onShown.description',
        ],
        [
          '<code>onClosed</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onClosed.description',
        ],
        [
          '<code>onClick</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onClick.description',
        ],
        [
          '<code>onTimeout</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onTimeout.description',
        ],
        [
          '<code>onPause</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onPause.description',
        ],
        [
          '<code>onResume</code>',
          '() =&gt; void',
          '<code class="neutral">undefined</code>',
          'components.toast.api.config.rows.onResume.description',
        ],
      ],
    },
  },
];
