import { ComponentSection } from '../../../../core';

export const MODAL_DIALOG_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-import',
    title: 'common.import',
    description: 'common.api.importService',
    anchor: 'api-import',
    examples: [
      {
        title: 'codeExamples.typescript',
        code: `import { ModalDialogService, ModalDialogRef, ModalDialogActionsService, ModalDialogFooterDirective } from 'nui';
import { MODAL_DIALOG_DATA, MODAL_DIALOG_REF, MODAL_DIALOG_CONFIG } from 'nui';
import type { ModalDialogConfig, ModalDialogResult, ModalDialogState } from 'nui';

@Component({ standalone: true })
export class MyComponent {
  private readonly modalDialog = inject(ModalDialogService);
}`,
        language: 'typescript',
      },
    ],
  },
  {
    id: 'api-service',
    title: 'components.modal-dialog.api.service.title',
    description: 'components.modal-dialog.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>open()</code>',
          'component: Type&lt;T&gt;, config?: ModalDialogConfig',
          'ModalDialogRef&lt;T, R&gt;',
          'components.modal-dialog.api.service.rows.openDynamic.description',
        ],
        [
          '<code>open()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openSimple.description',
        ],
        [
          '<code>openConfirm()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openConfirm.description',
        ],
        [
          '<code>openInfo()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openInfo.description',
        ],
        [
          '<code>openWarning()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openWarning.description',
        ],
        [
          '<code>openError()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openError.description',
        ],
        [
          '<code>openSuccess()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openSuccess.description',
        ],
        [
          '<code>openVerification()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openVerification.description',
        ],
        [
          '<code>openLoader()</code>',
          'config?: SimpleModalDialogConfig',
          'ModalDialogRef',
          'components.modal-dialog.api.service.rows.openLoader.description',
        ],
        [
          '<code>closeAll()</code>',
          "reason?: 'cancelled' | 'confirmed'",
          'void',
          'components.modal-dialog.api.service.rows.closeAll.description',
        ],
        [
          '<code>getById()</code>',
          'id: string',
          'ModalDialogRef | undefined',
          'components.modal-dialog.api.service.rows.getById.description',
        ],
        [
          '<code>openPanelsCount</code>',
          '-',
          'number',
          'components.modal-dialog.api.service.rows.openPanelsCount.description',
        ],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.modal-dialog.api.config.title',
    description: 'components.modal-dialog.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>title</code>', 'string', '-', 'components.modal-dialog.api.config.rows.title.description'],
        ['<code>iconTitle</code>', 'string', '-', 'components.modal-dialog.api.config.rows.iconTitle.description'],
        ['<code>message</code>', 'string', '-', 'components.modal-dialog.api.config.rows.message.description'],
        ['<code>data</code>', 'D', '-', 'components.modal-dialog.api.config.rows.data.description'],
        [
          '<code>width</code>',
          'string',
          "'500px'",
          'components.modal-dialog.api.config.rows.width.description',
        ],
        ['<code>minWidth</code>', 'string', '-', 'components.modal-dialog.api.config.rows.minWidth.description'],
        ['<code>height</code>', 'string', '-', 'components.modal-dialog.api.config.rows.height.description'],
        ['<code>minHeight</code>', 'string', '-', 'components.modal-dialog.api.config.rows.minHeight.description'],
        ['<code>maxWidth</code>', 'string', '-', 'components.modal-dialog.api.config.rows.maxWidth.description'],
        [
          '<code>modalType</code>',
          'ModalDialogType',
          'null',
          'components.modal-dialog.api.config.rows.modalType.description',
        ],
        ['<code>color</code>', 'NUIColor', '-', 'components.modal-dialog.api.config.rows.color.description'],
        [
          '<code>statusBar</code>',
          'ModalDialogStatusBar',
          '-',
          'components.modal-dialog.api.config.rows.statusBar.description',
        ],
        [
          '<code>canBeClosed</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.canBeClosed.description',
        ],
        [
          '<code>hasBackdrop</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.hasBackdrop.description',
        ],
        [
          '<code>backdropClass</code>',
          'string | string[]',
          '-',
          'components.modal-dialog.api.config.rows.backdropClass.description',
        ],
        [
          '<code>panelClass</code>',
          'string | string[]',
          '-',
          'components.modal-dialog.api.config.rows.panelClass.description',
        ],
        [
          '<code>closeOnBackdropClick</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.closeOnBackdropClick.description',
        ],
        [
          '<code>closeOnEscape</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.closeOnEscape.description',
        ],
        [
          '<code>closeOnRouteChange</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.closeOnRouteChange.description',
        ],
        [
          '<code>preventClose</code>',
          '() =&gt; boolean | Promise&lt;boolean&gt;',
          '-',
          'components.modal-dialog.api.config.rows.preventClose.description',
        ],
        [
          '<code>autoFocus</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.autoFocus.description',
        ],
        [
          '<code>animationDuration</code>',
          'number',
          '200',
          'components.modal-dialog.api.config.rows.animationDuration.description',
        ],
        [
          '<code>scrollStrategy</code>',
          "'block' | 'reposition'",
          "'block'",
          'components.modal-dialog.api.config.rows.scrollStrategy.description',
        ],
        [
          '<code>showHeader</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.showHeader.description',
        ],
        [
          '<code>showCloseButton</code>',
          'boolean',
          'true',
          'components.modal-dialog.api.config.rows.showCloseButton.description',
        ],
        [
          '<code>hideDefaultHeader</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.hideDefaultHeader.description',
        ],
        [
          '<code>hideDefaultFooter</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.hideDefaultFooter.description',
        ],
        [
          '<code>headerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '-',
          'components.modal-dialog.api.config.rows.headerTemplate.description',
        ],
        [
          '<code>footerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '-',
          'components.modal-dialog.api.config.rows.footerTemplate.description',
        ],
        [
          '<code>confirmText</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.confirmText.description',
        ],
        [
          '<code>cancelText</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.cancelText.description',
        ],
        [
          '<code>buttonsVariant</code>',
          'NUIVariant',
          '-',
          'components.modal-dialog.api.config.rows.buttonsVariant.description',
        ],
        [
          '<code>buttonsSize</code>',
          'NUISize',
          '-',
          'components.modal-dialog.api.config.rows.buttonsSize.description',
        ],
        [
          '<code>customButtons</code>',
          'ModalDialogCustomButton[]',
          '-',
          'components.modal-dialog.api.config.rows.customButtons.description',
        ],
        [
          '<code>showDefaultButtons</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.showDefaultButtons.description',
        ],
        [
          '<code>isLoading</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.isLoading.description',
        ],
        [
          '<code>loadingLabel</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.loadingLabel.description',
        ],
        [
          '<code>loadingSize</code>',
          'NUISize',
          '-',
          'components.modal-dialog.api.config.rows.loadingSize.description',
        ],
        [
          '<code>timeout</code>',
          'ModalDialogTimeoutOptions',
          '-',
          'components.modal-dialog.api.config.rows.timeout.description',
        ],
        [
          '<code>gestures</code>',
          'ModalDialogGestureOptions',
          '-',
          'components.modal-dialog.api.config.rows.gestures.description',
        ],
        [
          '<code>minimizable</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.config.rows.minimizable.description',
        ],
        ['<code>id</code>', 'string', '-', 'components.modal-dialog.api.config.rows.id.description'],
        [
          '<code>dockTabConfig</code>',
          'DockTabConfig',
          '-',
          'components.modal-dialog.api.config.rows.dockTabConfig.description',
        ],
        [
          '<code>contentTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '-',
          'components.modal-dialog.api.config.rows.contentTemplate.description',
        ],
        [
          '<code>templateContext</code>',
          'any',
          '-',
          'components.modal-dialog.api.config.rows.templateContext.description',
        ],
        [
          '<code>verificationText</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.verificationText.description',
        ],
        [
          '<code>verificationLabel</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.verificationLabel.description',
        ],
        [
          '<code>verificationPlaceholder</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.verificationPlaceholder.description',
        ],
        [
          '<code>verificationErrorMessage</code>',
          'string',
          '-',
          'components.modal-dialog.api.config.rows.verificationErrorMessage.description',
        ],
        [
          '<code>caseSensitive</code>',
          'boolean',
          '-',
          'components.modal-dialog.api.config.rows.caseSensitive.description',
        ],
      ],
    },
  },
  {
    id: 'api-custom-button',
    title: 'components.modal-dialog.api.customButton.title',
    description: 'components.modal-dialog.api.customButton.description',
    anchor: 'api-custom-button',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>text</code>', 'string', '-', 'components.modal-dialog.api.customButton.rows.text.description'],
        [
          '<code>color</code>',
          'NUIColor',
          '-',
          'components.modal-dialog.api.customButton.rows.color.description',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '-',
          'components.modal-dialog.api.customButton.rows.variant.description',
        ],
        [
          '<code>size</code>',
          'NUISize',
          '-',
          'components.modal-dialog.api.customButton.rows.size.description',
        ],
        [
          '<code>prefixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.customButton.rows.prefixIcon.description',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.customButton.rows.suffixIcon.description',
        ],
        [
          '<code>callback</code>',
          '(modalRef?: ModalDialogRef) =&gt; void | Promise&lt;void&gt;',
          '-',
          'components.modal-dialog.api.customButton.rows.callback.description',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.customButton.rows.disabled.description',
        ],
        [
          '<code>loading</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.customButton.rows.loading.description',
        ],
        [
          '<code>closeOnClick</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.customButton.rows.closeOnClick.description',
        ],
        [
          '<code>class</code>',
          'string',
          '-',
          'components.modal-dialog.api.customButton.rows.class.description',
        ],
        [
          '<code>ariaLabel</code>',
          'string',
          '-',
          'components.modal-dialog.api.customButton.rows.ariaLabel.description',
        ],
      ],
    },
  },
  {
    id: 'api-modal-action',
    title: 'components.modal-dialog.api.modalAction.title',
    description: 'components.modal-dialog.api.modalAction.description',
    anchor: 'api-modal-action',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>label</code>',
          'string',
          '-',
          'components.modal-dialog.api.modalAction.rows.label.description',
        ],
        [
          '<code>prefixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.modalAction.rows.prefixIcon.description',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.modalAction.rows.suffixIcon.description',
        ],
        [
          '<code>color</code>',
          'NUIColor',
          '-',
          'components.modal-dialog.api.modalAction.rows.color.description',
        ],
        [
          '<code>variant</code>',
          'NUIVariant',
          '-',
          'components.modal-dialog.api.modalAction.rows.variant.description',
        ],
        ['<code>size</code>', 'NUISize', '-', 'components.modal-dialog.api.modalAction.rows.size.description'],
        [
          '<code>handler</code>',
          '() =&gt; void | Promise&lt;void&gt;',
          '-',
          'components.modal-dialog.api.modalAction.rows.handler.description',
        ],
        [
          '<code>disabled</code>',
          'boolean | (() =&gt; boolean)',
          'false',
          'components.modal-dialog.api.modalAction.rows.disabled.description',
        ],
        [
          '<code>loading</code>',
          'boolean | (() =&gt; boolean)',
          'false',
          'components.modal-dialog.api.modalAction.rows.loading.description',
        ],
        [
          '<code>loadingPosition</code>',
          "'start' | 'end'",
          "'start'",
          'components.modal-dialog.api.modalAction.rows.loadingPosition.description',
        ],
        [
          '<code>width</code>',
          "'auto' | 'full'",
          "'auto'",
          'components.modal-dialog.api.modalAction.rows.width.description',
        ],
        [
          '<code>class</code>',
          'string',
          '-',
          'components.modal-dialog.api.modalAction.rows.class.description',
        ],
      ],
    },
  },
  {
    id: 'api-actions-service',
    title: 'components.modal-dialog.api.actionsService.title',
    description: 'components.modal-dialog.api.actionsService.description',
    anchor: 'api-actions-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>register()</code>',
          'actions: ModalDialogAction[]',
          'void',
          'components.modal-dialog.api.actionsService.rows.register.description',
        ],
        [
          '<code>add()</code>',
          'action: ModalDialogAction',
          'void',
          'components.modal-dialog.api.actionsService.rows.add.description',
        ],
        [
          '<code>update()</code>',
          'index: number, partial: Partial&lt;ModalDialogAction&gt;',
          'void',
          'components.modal-dialog.api.actionsService.rows.update.description',
        ],
        [
          '<code>clear()</code>',
          '-',
          'void',
          'components.modal-dialog.api.actionsService.rows.clear.description',
        ],
        [
          '<code>registerFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt; | null',
          'void',
          'components.modal-dialog.api.actionsService.rows.registerFooterTemplate.description',
        ],
      ],
    },
  },
  {
    id: 'api-footer-directive',
    title: 'components.modal-dialog.api.footerDirective.title',
    description: 'components.modal-dialog.api.footerDirective.description',
    anchor: 'api-footer-directive',
    note: {
      type: 'info',
      content: 'components.modal-dialog.api.footerDirective.note',
    },
  },
  {
    id: 'api-ref',
    title: 'components.modal-dialog.api.ref.title',
    description: 'components.modal-dialog.api.ref.description',
    anchor: 'api-ref',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>close()</code>',
          'result?: ModalDialogResult',
          'Promise&lt;void&gt;',
          'components.modal-dialog.api.ref.rows.close.description',
        ],
        ['<code>minimize()</code>', '-', 'void', 'components.modal-dialog.api.ref.rows.minimize.description'],
        ['<code>restore()</code>', '-', 'void', 'components.modal-dialog.api.ref.rows.restore.description'],
        [
          '<code>canTransitionTo()</code>',
          'newState: ModalDialogState',
          'boolean',
          'components.modal-dialog.api.ref.rows.canTransitionTo.description',
        ],
        [
          '<code>updateTitle()</code>',
          'title: string',
          'void',
          'components.modal-dialog.api.ref.rows.updateTitle.description',
        ],
        [
          '<code>updateHeaderTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'components.modal-dialog.api.ref.rows.updateHeaderTemplate.description',
        ],
        [
          '<code>updateFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'components.modal-dialog.api.ref.rows.updateFooterTemplate.description',
        ],
        [
          '<code>afterOpened()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.modal-dialog.api.ref.rows.afterOpened.description',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;ModalDialogResult | undefined&gt;',
          'components.modal-dialog.api.ref.rows.afterClosed.description',
        ],
        [
          '<code>backdropClick()</code>',
          '-',
          'Observable&lt;MouseEvent&gt;',
          'components.modal-dialog.api.ref.rows.backdropClick.description',
        ],
        [
          '<code>keydownEvents()</code>',
          '-',
          'Observable&lt;KeyboardEvent&gt;',
          'components.modal-dialog.api.ref.rows.keydownEvents.description',
        ],
        [
          '<code>stateChanged()</code>',
          '-',
          'Observable&lt;ModalDialogState&gt;',
          'components.modal-dialog.api.ref.rows.stateChanged.description',
        ],
        [
          '<code>closePrevented()</code>',
          '-',
          'Observable&lt;void&gt;',
          'components.modal-dialog.api.ref.rows.closePrevented.description',
        ],
      ],
    },
  },
  {
    id: 'api-ref-properties',
    title: 'components.modal-dialog.api.refProperties.title',
    description: 'components.modal-dialog.api.refProperties.description',
    anchor: 'api-ref-properties',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>id</code>', 'string', '-', 'components.modal-dialog.api.refProperties.rows.id.description'],
        [
          '<code>componentInstance</code>',
          'T | null',
          'null',
          'components.modal-dialog.api.refProperties.rows.componentInstance.description',
        ],
        ['<code>config</code>', 'ModalDialogConfig', '-', 'components.modal-dialog.api.refProperties.rows.config.description'],
        ['<code>state</code>', 'ModalDialogState', "'opening'", 'components.modal-dialog.api.refProperties.rows.state.description'],
        ['<code>isOpen</code>', 'boolean', '-', 'components.modal-dialog.api.refProperties.rows.isOpen.description'],
        ['<code>isClosed</code>', 'boolean', '-', 'components.modal-dialog.api.refProperties.rows.isClosed.description'],
        ['<code>isMinimized</code>', 'boolean', '-', 'components.modal-dialog.api.refProperties.rows.isMinimized.description'],
        [
          '<code>stateHistory</code>',
          'ReadonlyArray&lt;ModalDialogState&gt;',
          '-',
          'components.modal-dialog.api.refProperties.rows.stateHistory.description',
        ],
      ],
    },
  },
  {
    id: 'api-dock-tab-config',
    title: 'components.modal-dialog.api.dockTabConfig.title',
    description: 'components.modal-dialog.api.dockTabConfig.description',
    anchor: 'api-dock-tab-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>label</code>',
          'string',
          '-',
          'components.modal-dialog.api.dockTabConfig.rows.label.description',
        ],
        [
          '<code>prefixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.dockTabConfig.rows.prefixIcon.description',
        ],
        [
          '<code>suffixIcon</code>',
          'string',
          '-',
          'components.modal-dialog.api.dockTabConfig.rows.suffixIcon.description',
        ],
        [
          '<code>hideSuffixIcon</code>',
          'boolean',
          'false',
          'components.modal-dialog.api.dockTabConfig.rows.hideSuffixIcon.description',
        ],
        [
          '<code>cssClass</code>',
          'string | string[]',
          '-',
          'components.modal-dialog.api.dockTabConfig.rows.cssClass.description',
        ],
      ],
    },
  },
  {
    id: 'api-tokens',
    title: 'components.modal-dialog.api.tokens.title',
    description: 'components.modal-dialog.api.tokens.description',
    anchor: 'api-tokens',
    table: {
      headers: ['common.tables.token', 'common.tables.type', 'common.tables.description'],
      rows: [
        [
          '<code>MODAL_DIALOG_DATA</code>',
          'InjectionToken&lt;D&gt;',
          'components.modal-dialog.api.tokens.rows.MODAL_DIALOG_DATA.description',
        ],
        [
          '<code>MODAL_DIALOG_REF</code>',
          'InjectionToken&lt;ModalDialogRef&gt;',
          'components.modal-dialog.api.tokens.rows.MODAL_DIALOG_REF.description',
        ],
        [
          '<code>MODAL_DIALOG_CONFIG</code>',
          'InjectionToken&lt;ModalDialogConfig&gt;',
          'components.modal-dialog.api.tokens.rows.MODAL_DIALOG_CONFIG.description',
        ],
      ],
    },
  },
];
