import { ComponentSection } from '../../../../core';

export const MODAL_DIALOG_API_SECTIONS: ComponentSection[] = [
  {
    id: 'api-service',
    title: 'components.modal-dialog.api.service.title',
    description: 'components.modal-dialog.api.service.description',
    anchor: 'api-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>open()</code>',
          'component: Type&lt;T&gt;, config?: ModalDialogConfig',
          'ModalDialogRef&lt;T, R&gt;',
          'Opens a modal with a dynamic component',
        ],
        [
          '<code>open()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a simple message/HTML modal',
        ],
        [
          '<code>openConfirm()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a confirm dialog (type: confirm)',
        ],
        [
          '<code>openInfo()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens an info dialog',
        ],
        [
          '<code>openWarning()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a warning dialog',
        ],
        [
          '<code>openError()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens an error dialog',
        ],
        [
          '<code>openSuccess()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a success dialog',
        ],
        [
          '<code>openVerification()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a text-verification dialog',
        ],
        [
          '<code>openLoader()</code>',
          'config: SimpleModalDialogConfig',
          'ModalDialogRef',
          'Opens a loading spinner modal',
        ],
        ['<code>closeAll()</code>', '-', 'void', 'Closes all open modals'],
      ],
    },
  },
  {
    id: 'api-config',
    title: 'components.modal-dialog.api.config.title',
    description: 'components.modal-dialog.api.config.description',
    anchor: 'api-config',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>title</code>', 'string', '-', 'Modal title shown in the header'],
        ['<code>message</code>', 'string', '-', 'Simple text message for the body (simple modals)'],
        ['<code>htmlContent</code>', 'string', '-', 'Sanitized HTML content for the body'],
        [
          '<code>modalType</code>',
          'ModalDialogType',
          'null',
          'Semantic type: confirm | info | warning | danger | success | verification',
        ],
        ['<code>color</code>', 'NUIColor', '-', 'Button/accent color'],
        ['<code>width</code>', 'string', "'500px'", 'CSS width of the modal panel'],
        ['<code>minimizable</code>', 'boolean', 'false', 'Allows minimizing the modal to the dock'],
        [
          '<code>preventClose</code>',
          'boolean',
          'false',
          'Prevents the modal from being closed (hides close button and blocks gestures)',
        ],
        [
          '<code>bodyTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '-',
          'TemplateRef for the body, takes priority over message and htmlContent. Used with <code>templateContext</code> to pass context data.',
        ],
        ['<code>templateContext</code>', 'any', '-', 'Context object for the body template'],
        ['<code>id</code>', 'string', '-', 'Required when minimizable: true (singleton key)'],
        ['<code>hasBackdrop</code>', 'boolean', 'true', 'Show backdrop overlay'],
        ['<code>closeOnBackdropClick</code>', 'boolean', 'true', 'Close on backdrop click'],
        ['<code>closeOnEscape</code>', 'boolean', 'true', 'Close on Escape key'],
        ['<code>closeOnRouteChange</code>', 'boolean', 'false', 'Auto-close on route navigation'],
        [
          '<code>timeout</code>',
          'ModalDialogTimeoutOptions',
          '-',
          'Auto-close countdown with progress bar',
        ],
        [
          '<code>gestures</code>',
          'ModalDialogGestureOptions',
          '-',
          'Touch swipe gestures configuration',
        ],
        [
          '<code>statusBar</code>',
          'ModalDialogStatusBar',
          '-',
          'Colored border stripe on one side of the modal',
        ],
        [
          '<code>customButtons</code>',
          'ModalDialogCustomButton[]',
          '-',
          'Custom footer buttons (highest priority)',
        ],
        [
          '<code>footerTemplate</code>',
          'TemplateRef&lt;any&gt;',
          '-',
          'TemplateRef for the footer (lower priority than directive or customButtons)',
        ],
        ['<code>confirmText</code>', 'string', '-', 'Custom label for the confirm button'],
        ['<code>cancelText</code>', 'string', '-', 'Custom label for the cancel button'],
        [
          '<code>canBeClosed</code>',
          'boolean',
          'true',
          'If false, hides the close button and blocks all close gestures (use for loaders)',
        ],
        ['<code>verificationText</code>', 'string', '-', 'Text the user must type to confirm'],
        ['<code>data</code>', 'D', '-', 'Data injected via MODAL_DIALOG_DATA token'],
      ],
    },
  },
  {
    id: 'api-custom-button',
    title: 'components.modal-dialog.api.custom-button.title',
    description: 'components.modal-dialog.api.custom-button.description',
    anchor: 'api-custom-button',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>text</code>', 'string', '-', 'Button label (required)'],
        ['<code>color</code>', 'NUIColor', '-', 'Button color'],
        ['<code>variant</code>', 'NUIVariant', '-', 'Button variant (solid, outline, ghost)'],
        ['<code>size</code>', 'NUISize', '-', 'Button size'],
        ['<code>prefixIcon</code>', 'string', '-', 'Remix Icon class for prefix icon'],
        ['<code>suffixIcon</code>', 'string', '-', 'Remix Icon class for suffix icon'],
        [
          '<code>callback</code>',
          '(modalRef?: ModalDialogRef) =&gt; void | Promise&lt;void&gt;',
          '-',
          'Click handler (required)',
        ],
        [
          '<code>disabled</code>',
          'boolean',
          'false',
          'Static disabled state (evaluated once at open time)',
        ],
        [
          '<code>loading</code>',
          'boolean',
          'false',
          'Static loading state (evaluated once at open time)',
        ],
        [
          '<code>closeOnClick</code>',
          'boolean',
          'false',
          'Auto-close the modal after the callback runs',
        ],
        ['<code>class</code>', 'string', '-', 'Additional CSS classes'],
        ['<code>ariaLabel</code>', 'string', '-', 'Accessible label for the button'],
      ],
    },
  },
  {
    id: 'api-modal-action',
    title: 'components.modal-dialog.api.modal-action.title',
    description: 'components.modal-dialog.api.modal-action.description',
    anchor: 'api-modal-action',
    table: {
      headers: [
        'common.tables.property',
        'common.tables.type',
        'common.tables.default',
        'common.tables.description',
      ],
      rows: [
        ['<code>label</code>', 'string', '-', 'Button label (required)'],
        ['<code>prefixIcon</code>', 'string', '-', 'Remix Icon class for prefix icon'],
        ['<code>suffixIcon</code>', 'string', '-', 'Remix Icon class for suffix icon'],
        ['<code>color</code>', 'NUIColor', '-', 'Button color'],
        ['<code>variant</code>', 'NUIVariant', '-', 'Button variant (solid, outline, ghost)'],
        ['<code>size</code>', 'NUISize', '-', 'Button size'],
        [
          '<code>handler</code>',
          '() =&gt; void | Promise&lt;void&gt;',
          '-',
          'Click handler (required)',
        ],
        [
          '<code>disabled</code>',
          'boolean | (() =&gt; boolean)',
          'false',
          'Static boolean or reactive getter — re-evaluated every CD cycle',
        ],
        [
          '<code>loading</code>',
          'boolean | (() =&gt; boolean)',
          'false',
          'Static boolean or reactive getter — re-evaluated every CD cycle',
        ],
        ['<code>loadingPosition</code>', "'start' | 'end'", 'start', 'Loading spinner position'],
        ['<code>width</code>', "'auto' | 'full'", 'auto', 'Button width'],
        ['<code>class</code>', 'string', '-', 'Additional CSS classes'],
      ],
    },
  },
  {
    id: 'api-actions-service',
    title: 'components.modal-dialog.api.actions-service.title',
    description: 'components.modal-dialog.api.actions-service.description',
    anchor: 'api-actions-service',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>register()</code>',
          'actions: ModalDialogAction[]',
          'void',
          'Registers a set of footer actions, replacing any existing ones',
        ],
        [
          '<code>add()</code>',
          'action: ModalDialogAction',
          'void',
          'Adds a single action to the existing set',
        ],
        [
          '<code>update()</code>',
          'index: number, partial: Partial&lt;ModalDialogAction&gt;',
          'void',
          'Updates an action by its index (partial patch)',
        ],
        ['<code>clear()</code>', '-', 'void', 'Removes all registered actions'],
        [
          '<code>registerFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt; | null',
          'void',
          'Registers a TemplateRef as full footer (overrides actions; lower priority than directive)',
        ],
      ],
    },
  },
  {
    id: 'api-footer-directive',
    title: 'components.modal-dialog.api.footer-directive.title',
    description: 'components.modal-dialog.api.footer-directive.description',
    anchor: 'api-footer-directive',
    note: {
      type: 'info',
      content: 'components.modal-dialog.api.footer-directive.note',
    },
  },
  {
    id: 'api-ref',
    title: 'components.modal-dialog.api.ref.title',
    description: 'components.modal-dialog.api.ref.description',
    anchor: 'api-ref',
    table: {
      headers: [
        'common.tables.method',
        'common.tables.parameters',
        'common.tables.returns',
        'common.tables.description',
      ],
      rows: [
        [
          '<code>close()</code>',
          'result?: ModalDialogResult',
          'void',
          'Closes the modal and emits result',
        ],
        ['<code>minimize()</code>', '-', 'void', 'Minimizes the modal to the dock'],
        ['<code>restore()</code>', '-', 'void', 'Restores a minimized modal'],
        ['<code>updateTitle()</code>', 'title: string', 'void', 'Updates the panel title'],
        [
          '<code>updateHeaderTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the header template',
        ],
        [
          '<code>updateFooterTemplate()</code>',
          'template: TemplateRef&lt;any&gt;',
          'void',
          'Updates the footer template',
        ],
        [
          '<code>afterOpened()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emits once when the modal finishes opening',
        ],
        [
          '<code>afterClosed()</code>',
          '-',
          'Observable&lt;ModalDialogResult | undefined&gt;',
          'Emits once when the modal closes',
        ],
        [
          '<code>backdropClick()</code>',
          '-',
          'Observable&lt;MouseEvent&gt;',
          'Emits on each backdrop click',
        ],
        [
          '<code>keydownEvents()</code>',
          '-',
          'Observable&lt;KeyboardEvent&gt;',
          'Emits keyboard events from the overlay',
        ],
        [
          '<code>stateChanged()</code>',
          '-',
          'Observable&lt;ModalDialogState&gt;',
          'Emits on every state transition',
        ],
        [
          '<code>closePrevented()</code>',
          '-',
          'Observable&lt;void&gt;',
          'Emits when close is blocked (canBeClosed: false)',
        ],
        ['<code>id</code>', 'string', 'Unique panel ID'],
        ['<code>componentInstance</code>', 'T | null', 'Instance of the loaded component'],
        ['<code>config</code>', 'ModalDialogConfig', 'Panel configuration'],
        ['<code>state</code>', 'ModalDialogState', 'Current panel state'],
        ['<code>isOpen</code>', 'boolean', 'true if panel is open or opening'],
        ['<code>isClosed</code>', 'boolean', 'true if panel is closed or closing'],
        ['<code>isMinimized</code>', 'boolean', 'true if panel is minimized'],
        [
          '<code>stateHistory</code>',
          'ReadonlyArray&lt;ModalDialogState&gt;',
          'History of panel states',
        ],
      ],
    },
  },
  {
    id: 'api-tokens',
    title: 'components.modal-dialog.api.tokens.title',
    description: 'components.modal-dialog.api.tokens.description',
    anchor: 'api-tokens',
    table: {
      headers: ['common.tables.token', 'common.tables.type', 'common.tables.description'],
      rows: [
        [
          '<code>MODAL_DIALOG_DATA</code>',
          'InjectionToken&lt;D&gt;',
          'Inject typed data in the dynamic component',
        ],
        [
          '<code>MODAL_DIALOG_REF</code>',
          'InjectionToken&lt;ModalDialogRef&gt;',
          'Inject the modal reference in the shell or dynamic component',
        ],
        [
          '<code>MODAL_DIALOG_CONFIG</code>',
          'InjectionToken&lt;ModalDialogConfig&gt;',
          'Inject the full configuration object (read-only)',
        ],
      ],
    },
  },
];
